{% set name = "sumy" %}
{% set version = "0.11.0" %}
{% set py_ver = PY_VER %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sumy-{{ version }}.tar.gz
  sha256: 1c52dcfda3072d87c7ae85a100c53a93f5b1f758466a1a1369f86aff1bb0129d

build:
  number: 0
  noarch: python
  entry_points:
    - sumy = sumy.__main__:main
    - sumy-{{ py_ver }} = sumy.__main__:main
    - sumy_eval = sumy.evaluation.__main__:main
    - sumy_eval-{{ py_ver }} = sumy.evaluation.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - breadability >=0.1.20
    - docopt >=0.6.1,<0.7
    - nltk >=3.0.2
    - pycountry >=18.2.23
    - python >=3.5
    - requests >=2.7.0

test:
  imports:
    - sumy
    - sumy.evaluation
  commands:
    - pip check
    - sumy --help
    - sumy-{{ py_ver }} --help
    - sumy_eval --help
    - sumy_eval-{{ py_ver }} --help
  requires:
    - pip

about:
  home: https://github.com/miso-belica/sumy
  summary: Module for automatic summarization of text documents and HTML pages.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - nicornk
    - tobiasploetz
